name: BW-EA Organizations Base CI/CD Workflow Template

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]
  workflow_dispatch:
  # Needed to execute workflow manually -> https://docs.github.com/en/actions/using-workflows/manually-running-a-workflow
  
jobs:
  build:
    runs-on: ubuntu-latest
    permissions: # Permissions block is optional, useful for dependabot checks 
    # https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs
      checks: write
      contents: read
      
    steps:
      - uses: actions/checkout@v4 # https://github.com/actions/checkout

      - name: Set up Java version
        uses: actions/setup-java@v4 # https://github.com/actions/setup-java
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: ${{ env.DISTRIBUTION }}
          cache: 'maven'

      - name: Maven Build
        run: mvn -B package --file rest/pom.xml
        
      - name: Run Unit tests
        run: mvn test --batch-mode --fail-at-end
      
      - name: Publish Test Report
        if: success() || failure()
        uses: scacap/action-surefire-report@v1
        
      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v3
        with:
          name: ea-java-demo
          path: '${{ github.workspace }}${{env.SUB_PROJECT}}/target/*.jar'
          
  deploy:
    permissions:
      contents: none
    runs-on: ubuntu-latest
    needs: build
    environment:
      # environment documenataion:
      # https://docs.github.com/en/actions/deployment/targeting-different-environments/using-environments-for-deployment
      name: 'Development'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3 # https://github.com/actions/download-artifact
        with:
          name: ea-java-demo

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3 # https://github.com/Azure/webapps-deploy
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: '*.jar'
